services:
  fomenki-bot:
    image: lobanovsky/fomenki-bot:${TAG}
    container_name: fomenki-bot
    restart: always
    environment:
      TZ: Europe/Moscow
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      BACKEND_URL: ${BACKEND_URL}
      FOMENKI_API_KEY: ${FOMENKI_API_KEY}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      WEBHOOK_PORT: ${WEBHOOK_PORT:-8084}
    ports:
      - "${WEBHOOK_PORT:-8084}:${WEBHOOK_PORT:-8084}"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
